spring.application.name=appbancaria
spring.datasource.url=jdbc:postgresql://localhost:5432/banco_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=banco_user
spring.datasource.password=banco_pass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update




spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

